### ISSUE TITLE
Should `nixpkgs/overlays.nix` contain an overlay referring to the pinned `nixpkgs`?

### ISSUE THREAD

**Issue by bzm3r** [infinisil/sanix#1]
I (roughly) understand that the configuration's builder will know to look for the appropriate `nixpkgs` based on work done by the `rebuild` script to set `NIX_PATH` appropriately.

Therefore, there should not be the need to add the following to `nixpkgs/overlays.nix`:

```
  (
    let
      sources = ./niv/source.json;
    in
    self: _super: {
      inherit (sources) nixpkgs;
    }
  )
```

But I'm wondering if this is useful regardless? For example: if for some reason, `NIX_PATH` changes between when `rebuild` sets it, and the configuration is built, then the configuration will still end up using the right `nixpkgs` imported by `npins`/`niv`/etc., rather than whatever is pointed to by `NIX_PATH`?

Also, I'm wondering if there is a way to obviate `NIX_PATH` entirely....will have to look into how it is read currently in the `nixpkgs` repo, but it would be nice if we could point it to read from a file instead...

Some way to fix the `NIX_PATH` env var, essentially, and make it "immutable".

(One really silly/sad idea that comes to mind is a `systemd` unit that monitors changes to `NIX_PATH`...)

**Comment by infinisil** [comment]
> I (roughly) understand that the configuration's builder will know to look for the appropriate `nixpkgs` based on work done by the `rebuild` script to set `NIX_PATH` appropriately.
> 
> Therefore, there should not be the need to add the following to `nixpkgs/overlays.nix`:
> 
> ```
>   (
>     let
>       sources = ./niv/source.json;
>     in
>     self: _super: {
>       inherit (sources) nixpkgs;
>     }
>   )
> ```

I'm not a fan of this because it's a bit recursive/backwards. The top level is the `default.nix`, which imports Nixpkgs, configures it with overlays, and declares a NixOS system. If the Nixpkgs is set in overlays themselves, there can be cases where the recursive nature of that gives trouble. For example if you try to use

```nix
{ pkgs, ... }: {
  imports = [
    (pkgs.nixpkgs + "/nixos/modules/...")
  ];
}
```

This would fail because of how modules themselves can change `pkgs`.

Or what if you override `nixpkgs` to break overlays entirely? Would it still work then because you're using overlays themselves to define it?

**Comment by infinisil** [comment]
> Also, I'm wondering if there is a way to obviate `NIX_PATH` entirely....will have to look into how it is read currently in the `nixpkgs` repo, but it would be nice if we could point it to read from a file instead...

At least it can be "avoided" in the `rebuild` script by just using `-I` instead, which I just did: https://github.com/infinisil/sanix/commit/37b7f370e36f1a1e90f746e0a4f80582058f7d55

But really underneath `nixos-rebuild` is hardcoded to use `<nixpkgs/nixos>` with non-Flakes: https://github.com/NixOS/nixpkgs/blob/49cd2f2d1f1aeff17376d3ab52d4fc6e4caa7ed9/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L603

To avoid that we need some standardised way to configure Nixpkgs, and yes, Flakes is _one_ way to do that.

**Comment by infinisil** [comment]
Oh and regarding the hosts `NIX_PATH` in https://github.com/infinisil/sanix/blob/37b7f370e36f1a1e90f746e0a4f80582058f7d55/root.nix#L19-L23

This is there so commands work by default. Flakes got "rid" of that by introducing the Flakes registry, which is just a glorified version of the same impure NIX_PATH, see also https://github.com/NixOS/nix/issues/7422

**Comment by bzm3r** [comment]
> > Also, I'm wondering if there is a way to obviate `NIX_PATH` entirely....will have to look into how it is read currently in the `nixpkgs` repo, but it would be nice if we could point it to read from a file instead...
> 
> At least it can be "avoided" in the `rebuild` script by just using `-I` instead, which I just did: [37b7f37](https://github.com/infinisil/sanix/commit/37b7f370e36f1a1e90f746e0a4f80582058f7d55)
> 
> But really underneath `nixos-rebuild` is hardcoded to use `<nixpkgs/nixos>` with non-Flakes: https://github.com/NixOS/nixpkgs/blob/49cd2f2d1f1aeff17376d3ab52d4fc6e4caa7ed9/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L603
> 
> To avoid that we need some standardised way to configure Nixpkgs, and yes, Flakes is _one_ way to do that.

As far as `sanix` is considered, this standardized way would be `niv` or `npins`, right?

**Comment by infinisil** [comment]
Indeed :)

**Comment by bzm3r** [comment]
Okay! I think this is all clear to me, and I'm happy with the updated setup. Thank you!
